### ISSUE TITLE
Visual coding neuropixels live script

### ISSUE THREAD

**Issue by DylanMuir** [emeyers/Brain-Observatory-Toolbox#41] opened 2020-12-29 16:36 UTC
Production of a working MATLAB Live Script demonstrating a neuroscience analysis workflow for the Visual Coding-Neuropixels (https://portal.brain-map.org/explore/circuits/visual-coding- neuropixels) dataset with R2020b. This is expected to include but not be limited to:

- [x] access of the dataset contents
- [x] interactive selection of a subset of the data for analysis
- [x] a scientific output based on the analysis (e.g. a set of layer-specific tuning curves) based on that data
- [x] sufficient narrative text to explain the workflow.

**Comment by DylanMuir** [comment] 2021-01-14 13:11
@vijayiyer05 We need a nice image to illustrate the demo, as for the OPhys demo. How much of this can we use from the Allen website? Would you be comfortable to compose an illustration?

**Comment by DylanMuir** [comment] 2021-01-14 13:14
Initial draft of the demo in a4f9cf423a4dff8c93295e43097e7dd5d734d02f

**Comment by vijayiyer05** [comment] 2021-01-14 13:32
@DylanMuir Please follow the same approach as used in the OphysDemo for illustrations and narrative: 

- Include image credits where appropriate to the Allen Institute
- When referring to the overall resource, always name it in full as "Allen Brain Observatory". And give the citation upon the first reference in the file.
- Name the dataset ("Visual Coding - Neuropixels") completely and give its (separate) citation, upon its first reference in the file.

Since a composite image is stored in a separate standalone file, these same guidelines apply to that file, i.e. can see the credits and citations within the captions of the OphysDemo image.

**Comment by vijayiyer05** [comment] 2021-01-17 20:20
@DylanMuir  I believe this is in a pre-review state, so this is all just FYI.

I did a cursory and clean (cache rebuild) run-through on the draft from a4f9cf4. Shaping up nicely! 

Couple of notes:

* Good to see the brain structure acronyms decoded for humans. Curious if the same machinery can easily be applied for the Ophys side as well. That one still seems to have numeric structure IDs. 
* Good to see the clear display categories, including statement of cached status. Should consider if some of the developer phrases of cached and lazy loading should apply to the public API. One possibility might be to refer to this as a `gather `type operation, similar to the semantics for `gpuarray`s and tall arrays. To fully replicate semantics would require a new object to represent the "remote" state, which seems overkill for now. An intermediate idea might be to 1) update many of the access data verbs (including methods that invoke it underneath) to start with `gather` prefix and 2) to reframe 'not cached' as something more forward-looking like 'ready to gather' or something like that. 
* It runs mostly through, but I do get an error at the call to `fetch_pupil_data`. See below. 

![image](https://user-images.githubusercontent.com/23032671/104854592-97068f80-58d5-11eb-9ea2-3af1126f4e5e.png)

**Comment by DylanMuir** [comment] 2021-01-18 07:00
Runs now with no errors. Included an illustration.
@vijayiyer05 Can you suggest something else to add to the demo?

**Comment by vijayiyer05** [comment] 2021-01-21 03:23
@DylanMuir Bummer: I'm still running into the same error, at least with cached data. I'll try again (overnight) with cache rebuild. To sanity check, were you referencing commit the run-through is at commit cd7503?

**Comment by DylanMuir** [comment] 2021-01-22 07:55
@vijayiyer05 Yes that's correct — the latest commit on branch `iss41`

**Comment by vijayiyer05** [comment] 2021-01-22 15:40
@DylanMuir : Sadly still getting that same error at cd75036 , even after a cache rebuild. Will take a look over the weekend to see if there's some user error.

**Comment by DylanMuir** [comment] 2021-01-22 15:44
@vijayiyer05 Very surprising! I'm on R2020b, if that's relevant. I ran it previously on a clean cache, but I'll try again to see if I can spot anything.

**Comment by DylanMuir** [comment] 2021-01-23 12:39
@vijayiyer05 In commit 73608819fa4c92fa8cf0ecaeea774563ea6360d4 I ran through twice from a clean cache with no errors, on R2020b. Could you please check once more, and also confirm what version of Matlab you're running?

**Comment by vijayiyer05** [comment] 2021-01-23 15:52
@DylanMuir  Thx for update. About to check now (at commit 7360881), will let you know what I find. To confirm: have been using R2020b as well.

**Comment by vijayiyer05** [comment] 2021-01-23 17:57
@DylanMuir  Still running into the issue at 7360881 unfortunately. One sanity check question: what is the size of the file ecephys_session_742951821.nwb in your hands?  It's 2.85GB in mine. I remember from past that partial downloads of NWB files could occur (e.g. with spotty WiFi before I switched to a wired connection) and then give rise to issues downstream.

**Comment by vijayiyer05** [comment] 2021-01-23 18:17
@DylanMuir 

I may have figured it out. Are you running on a Mac or Linux box perchance? 

I've verified the particular H5 dataset in question exists within the cached NWB file accessed by the `fetch_pupil_data `file. 

The issue seems to be a slash direction issue. The offending call to `h5read `gets a backslached H5 path, whereas the H5 API requires forward slashes. 

Problem seems to originate at line 52 of `bot.nwb.table_from_datasets ` which uses a `filesep `command. Whereas that usually avoids OS dependency, in this case it may be introducing one.

**Comment by DylanMuir** [comment] 2021-01-24 18:47
@vijayiyer05 `bot.nwb.table_from_datasets()` uses `fullfile` to build an HDF5 path. Is there a better, Matlab-canonical way to build a valid HDF5 path that is truly cross-platform?

**Comment by vijayiyer05** [comment] 2021-01-25 13:58
@DylanMuir From what I'm reading, it seems HDF5 paths always use forward slashes (/) irrespective of OS. So I believe best way would be to simply hard-code e.g. `strNWBKey + "/" + strDSName`. The `fullfile `& `filesep `commands are for file system paths and introduce an OS dependence.

**Comment by vijayiyer05** [comment] 2021-01-27 04:28
@DylanMuir  I went ahead to fix this issue at f71e5ec. Probably idea of `fullfile` arose to be char vs string independent (since `table_from_datasets` is called with either at various points), and then ended up introducing an inadvertent OS dependency. In this case I've explicitly converted to string. A more canonical way would be to do the conversion up front via an arguments block specification (which will do natural conversions, such as char to string). But not so important for this function which is more internal in spirit at this time.

**Comment by vijayiyer05** [comment] 2021-01-27 04:38
@DylanMuir  As of f71e5ec, get mostly through the script but then run into another error downstream (see image below). Haven't had a chance yet to look into it more closely. 

![image](https://user-images.githubusercontent.com/23032671/105943528-76ee7300-602f-11eb-9a85-6cc081a0063f.png)

**Comment by DylanMuir** [comment] 2021-01-29 21:06
I was using `_ismemberhelper`, as suggested here: https://ch.mathworks.com/matlabcentral/answers/92533-how-do-i-perform-a-binary-search-of-a-presorted-array

Now I'm using `ismembc2`, which should be more portable.

**Comment by DylanMuir** [comment] 2021-01-29 21:07
@vijayiyer05 Please check if this works for you now, and we can merge

**Comment by vijayiyer05** [comment] 2021-01-30 03:04
@DylanMuir That explains & fixes it in my hands. About to merge. Created a fresh issue #52 for the finalization steps that we'll identify on Monday.

Note there's now a small list of things that will be a bit better under the hood in R2021a (I'm testing with the prerelease). Have  captured these in Issue #51. My current thinking is to designate the release for this project as v0.9 targeting R2020b; and then to target R2021a for a v1.0 release. Can discuss briefly after our upcoming session.

**Comment by vijayiyer05** [comment] 2021-01-30 03:12
@DylanMuir  Reopening momentarily to record that I did transiently observe a `webread ` error on the call to `probe.fetch_current_source_density`, on first run-through after the fix to `_ismemberhelper`. But this has not been reproduced and I've lost the error message, so closing again for now.

**Closed by vijayiyer05** 2021-01-30 03:12 UTC
Labels: documentation
